### ISSUE TITLE
IFA assessment folder path or assessment name cannot contain space

### ISSUE THREAD

**Issue by z10n0101** [HCL-TECH-SOFTWARE/ifa-client#2] opened 2019-10-07 09:55 UTC
If there is a space character in folder path of assessment file name IFA will get confused and fail to start with exception: File does not exist or is inaccessible.

![IFA space in filename](https://user-images.githubusercontent.com/32577597/66302438-39754c00-e8f9-11e9-935c-b2770fbd2824.PNG)
![IFA space in path](https://user-images.githubusercontent.com/32577597/66302444-3b3f0f80-e8f9-11e9-8b88-3c79732f4083.PNG)

**Comment by kaddmann** [comment] 2019-10-08 19:40
I am unable to reproduce this error. Have you tried the latest download of the client?

**Comment by kaddmann** [comment] 2019-10-28 17:52
Closing. Let me know if you are still hitting this and we will take a peek.

**Closed as completed** 2019-10-28 17:53 UTC

**Comment by z10n0101** [comment] 2019-10-29 10:03
Yap, it is working with latest version of the client. Thanks!
